version: '3.7'
services: 
  logstash:
    build: 
      dockerfile: ${PWD}/Dockerfile
      context: ${PWD}/
    environment:
      - LOGSTASH_JDBC_URL=jdbc:mysql://mysql:3306/tmpdb?useSSL=false
      - LOGSTASH_JDBC_DRIVER=com.mysql.cj.jdbc.Driver
      - LOGSTASH_JDBC_DRIVER_JAR_LOCATION=/usr/share/logstash/logstash-core/lib/jars/mysql-connector-java.jar
      - LOGSTASH_JDBC_USERNAME=root
      - LOGSTASH_JDBC_PASSWORD=admin
      - LOGSTASH_ELASTICSEARCH_HOST=http://127.0.0.1:9200
    volumes: 
      - ./mysql-jdbc-input-plugin.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - 9600:9600
      - 5044:5044

